"""empty message

Revision ID: 816b095eef28
Revises: f77a8df10f14
Create Date: 2021-01-04 14:47:55.157726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '816b095eef28'
down_revision = 'f77a8df10f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('isbn', sa.String(length=50), nullable=False))
    op.drop_column('book', 'ibsn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('ibsn', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('book', 'isbn')
    # ### end Alembic commands ###
